version: '3'

services:
  notebooks:
    image: jupyter/tensorflow-notebook
    
    volumes:
      - ./data:/data
      - ./:/code

    working_dir: /code/notebooks

    ports:
      - 8888:8888

    command: jupyter lab --no-browser --allow-root --ip 0.0.0.0 --NotebookApp.custom_display_url=http://localhost:8888
